spring.application.name=api-gateway
server.port=8080
gateway.api-key=crs-partner-key-2026
spring.cloud.gateway.server.webflux.routes[0].id=auth
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[1].id=courses
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/courses/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[2].id=registrations
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/registrations/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[3].id=public-courses
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/public/courses/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=RewritePath=/api/public/courses(?<segment>/?.*), /courses${segment}
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000,http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=Authorization,Content-Type,X-API-KEY
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
